# Top-level directory
TOP_DIR := ..

# Object file directory
OBJ_DIR := $(TOP_DIR)/obj

# Include module.mk to get the module-specific rules
include module.mk

# Targets
all: $(MODULE_OBJECTS)

clean:
	rm -f $(MODULE_OBJECTS)
